### ISSUE TITLE
Problems with breadcrumbs

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/opera#2]
Tested this theme out on http://themeswitcher.simplo.site/ and as of today, it has some major issues with breadcrumbs. We need to fix these.

![breadcrumbs](https://user-images.githubusercontent.com/3144571/108819293-49d6a700-7580-11eb-89b3-1bdc7b7af50b.png)

**Comment by bdalomgir** [comment]
@stpaultim I have fixed the breadcrumb separator issue and created a PR - https://github.com/TeamTriplo/opera/pull/15 and I merged the PR as well :smiley:

**Comment by stpaultim** [comment]
I merged this change from the Triplo repo into the this repo. Thanks @bdalomgir
