### ISSUE TITLE
Better handling of logos

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/opera#6]
Currently, we don't seem to have any space between the logo and the top of the page. This works fine for a transparent logo with some padding in the image, but if a logo is tightly cropped it's not going to look very good. 

![opera-logo](https://user-images.githubusercontent.com/3144571/108820857-670c7500-7582-11eb-9bb5-f204c9ec9619.png)

**Comment by bdalomgir** [comment]
@stpaultim I have fixed spacing problem between the logo and the top of the page, created a new PR - https://github.com/TeamTriplo/opera/pull/15, Please take a look.

**Comment by stpaultim** [comment]
@bdalomgir Fixed!
